title: "EUTC Documents"
remote_theme: pmarsceill/just-the-docs
color_scheme: "bedlam"
search_enabled: true
logo: "https://eutc.azureedge.net/img/logos/bedlam-eutc/bedlam-eutc-lateral-black.svg"
aux_links:
  "Bedlam Theatre Main Website": 
    - "https://www.bedlamtheatre.co.uk/"
aux_links_new_tab: true
footer_content: "Copyright &copy; Edinburgh University Theatre Company. Bedlam Theatre, Edinburgh, EH1 1EZ, Scotland."